### ISSUE TITLE
RuntimeError: unexpected EOF, expected 2095002 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by fadeawaygod** [monpa-team/monpa#1]
env
- win10
- python 3.7.3
- torch==1.1.0

my code:

```
import monpa
sentence = "蔡英文總統今天受邀參加台北市政府所舉辦的陽明山馬拉松比賽。"
result = monpa.cut(sentence)

for t in result:
    print(t)
```

Result:

```
+---------------------------------------------------------------------+
  Welcome to use MONPA: Multi-Objective NER POS Annotator for Chinese
+---------------------------------------------------------------------+
Good, we can found the model file
07/25/2019 14:17:06 - INFO - monpa -   running on device cpu
Traceback (most recent call last):
  File "c:\Users\Tom Chen\.vscode\extensions\ms-python.python-2019.5.18875\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\Tom Chen\.vscode\extensions\ms-python.python-2019.5.18875\pythonFiles\lib\python\ptvsd\__main__.py", line 434, in main
    run()
  File "c:\Users\Tom Chen\.vscode\extensions\ms-python.python-2019.5.18875\pythonFiles\lib\python\ptvsd\__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "c:\programdata\anaconda3\Lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "c:\programdata\anaconda3\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "c:\programdata\anaconda3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Codes\PythonPlayground\monpa_test.py", line 1, in <module>
    import monpa
  File "d:\Codes\PythonPlayground\env\lib\site-packages\monpa\__init__.py", line 128, in <module>
    checkpoint_dict = torch.load(args.model, map_location='cpu')
  File "d:\Codes\PythonPlayground\env\lib\site-packages\torch\serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "d:\Codes\PythonPlayground\env\lib\site-packages\torch\serialization.py", line 581, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 2095002 more bytes. The file might be corrupted.
```

Note:
This error only occurs at first time

**Comment by windyeh** [comment]
Thank you for trying and issuing.
Since the model downloading is "stream" turn on, I am afraid that may caused by an incomplete model download at your 1st try. In case happen again, please remove downloaded model file (at monpa package) for initial download. 
Next version, we may consider to add a checking mechanism.

**Comment by wthomasu** [comment]
Yes, same problem, but after removing the file "model-511.pt" in model , please execute "import monpa" again, so you can see the message.
+---------------------------------------------------------------------+
  Welcome to MONPA: Multi-Objective NER POS Annotator for Chinese
+---------------------------------------------------------------------+
首次使用 monpa 將會直接下載 model 檔，約 200MB，並儲存於 monpa package 資料夾，下次就不需再下載。
At first time using, we will automatically download the model file (around 200MB).
Total  file  size: 216681674 KB
#########
07/26/2019 14:30:06 - INFO - monpa -   running on device cpu
#已完成 monpa model 下載，歡迎使用。Download completed.

**Comment by windyeh** [comment]
Yes.
The incomplete download model file can cause most of those issues, please remove downloaded model file (at monpa package) and execute "import monpa" again to invoke new download.

**Comment by windyeh** [comment]
find where the monpa package at your local computer by 
```
import os
import monpa

os.path.abspath(monpa.__file__)
```
